### ISSUE TITLE
`BackoffTimer#wait` should return either a `Result` or `Option`

### ISSUE THREAD

**Issue by jaredonline** [mrtazz/BackoffTimer#1]
I'm leaning pretty strongly towards `Result`. Its idiomatic in Rust to not make the caller of a function need to be aware of the internals to handle it properly. Calling `#wait`, the caller shouldn't need to know that a return of `0` is an error condition (it also potentially conflates the case where it waited for 0 seconds), instead they should be forced to handle this by the type system.

`#wait` Should probably return a [`std::result::Result`](https://doc.rust-lang.org/std/result/enum.Result.html).

```rust
put struct WaitError;

fn wait() -> Result<u64, WaitError> {
}
```

Then a caller would:

```rust
match timer.wait() {
  Ok(time_waited) => {},
  Err(e) => {},
}
```

[Here's an example](https://doc.rust-lang.org/src/core/up/src/libcore/fmt/mod.rs.html#62) of a custom error type that the formatting library uses.

If you wanted to keep the requirement on `std` out of your library, you could also use [`core::result::Result`](https://doc.rust-lang.org/core/result/enum.Result.html)

**Comment by mrtazz** [comment]
@jaredonline thanks for the issue!
